name = "ctohm-edge-resizer"
type = "javascript"
workers_dev = true
compatibility_date = "2021-12-05"
route = ""
account_id = ""
api_token = ""
zone_id = ""

[vars]
  WORKER_ENV = "production"
  DEBUG = true
  ROUTE_PREFIX='/' # e.g. /thumbnails
  RELEASE = "7d2427a"
  TIMESTAMP = ""
  MAX_AGE = "1y"

[build]
  command = "[ -z \"$ROUTE_PREFIX\" ] && npx esbuild src/index.ts --bundle --format=cjs --outfile=dist/worker.js || npx esbuild src/index.ts --bundle --format=cjs --outfile=dist/worker.js  --define:ROUTE_PREFIX=$ROUTE_PREFIX"

  [build.upload]
    format = "service-worker"

